name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v3

      - run: bun run fmt:check

      - run: bun run lint
